name: Deploy (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug whoami and target perms
        run: |
          whoami
          id
          ls -la /var/www/luminet/luminet-web || true

      - name: Sync to live dir (rsync, no perms/owner/group changes)
        run: |
          rsync -az --delete \
            --no-perms --no-owner --no-group --omit-dir-times \
            --exclude="node_modules" \
            --exclude=".next" \
            ./ /var/www/luminet/luminet-web/

      - name: Install dependencies
        working-directory: /var/www/luminet/luminet-web
        run: npm ci --omit=dev

      - name: Apply DB migrations
        working-directory: /var/www/luminet/luminet-web
        run: npx prisma migrate deploy || true

      - name: Build project
        working-directory: /var/www/luminet/luminet-web
        run: npm run build

      - name: Restart PM2
        working-directory: /var/www/luminet/luminet-web
        run: |
          pm2 describe luminet >/dev/null 2>&1 && pm2 restart luminet || pm2 start ecosystem.config.js

      - name: Health check
        run: curl -fsS http://127.0.0.1:3000/api/ping || (pm2 logs --lines 120 && exit 1)