name: Deploy (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    concurrency:
      group: deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Sync to live dir (keep prisma/.env and DB)
        run: |
          rsync -az --delete \
            --no-perms --no-owner --no-group --omit-dir-times \
            --exclude="node_modules" \
            --exclude=".next" \
            --exclude="data/luminet.db" \
            --exclude="prisma/.env" \
            ./ /var/www/luminet/luminet-web/

      - name: Install deps
        working-directory: /var/www/luminet/luminet-web
        run: npm ci

      - name: Generate Prisma Client
        working-directory: /var/www/luminet/luminet-web
        run: npx prisma generate

      - name: Apply DB migrations
        working-directory: /var/www/luminet/luminet-web
        env:
          DATABASE_URL: "file:./data/luminet.db"
        run: npx prisma migrate deploy || true

      - name: Build
        working-directory: /var/www/luminet/luminet-web
        run: npm run build --verbose

      - name: Verify build artifact
        working-directory: /var/www/luminet/luminet-web
        run: |
          ls -la .next || (echo "No .next produced" && exit 1)
          test -f .next/BUILD_ID || (echo "Missing BUILD_ID" && exit 1)

      - name: Prune dev deps (optional)
        working-directory: /var/www/luminet/luminet-web
        run: npm prune --omit=dev

      - name: Restart PM2
        working-directory: /var/www/luminet/luminet-web
        run: |
          pm2 describe luminet >/dev/null 2>&1 && pm2 restart luminet --update-env || pm2 start ecosystem.config.js
          pm2 save

      - name: Health check (retry)
        run: |
          for i in {1..15}; do
            curl -fsS http://127.0.0.1:3000/api/ping && exit 0
            sleep 2
          done
          echo "Health check failed after retries"; pm2 logs --lines 200; exit 1